### ISSUE TITLE
Pagination Bug

### ISSUE THREAD

**Issue by PedroCiva** [sain0136/myrotary-projects#477]
Bug Description:
When the value selected on the dropdown (the one that specifies amount of results to be displayed in each page) is higher than the total results the page goes blank, as if there was no data available for the table to display. 

The bug happens on ALL pages, EXCEPT when the user is on the first page.

**Comment by sain0136** [comment]
@PedroCiva  
So, this bug occurred when the pagination object limit was updated to be bigger than the total number of records, which will of course break the query if it's on a page that doesn't have any records. I could have solved it many ways, but I just decided that when you change the limit, you return to page 1 for an easy solution.
